"""Add custom_title column to FeedForUser

Revision ID: 4066885876ac
Revises: 
Create Date: 2024-11-22 11:50:05.978926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4066885876ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_for_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_for_user', schema=None) as batch_op:
        batch_op.drop_column('custom_title')

    # ### end Alembic commands ###
