"""Add author column to Article

Revision ID: 743af1d2cecb
Revises: 005f16091365
Create Date: 2024-11-22 12:44:53.087314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743af1d2cecb'
down_revision = '005f16091365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
