"""Add custom_description column to FeedForUser

Revision ID: 84f4d3cb3eab
Revises: 4066885876ac
Create Date: 2024-11-22 11:52:25.274101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f4d3cb3eab'
down_revision = '4066885876ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_for_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_for_user', schema=None) as batch_op:
        batch_op.drop_column('custom_description')

    # ### end Alembic commands ###
